# Generated by Django 5.2.1 on 2025-05-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0003_alter_password_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordfolder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
